{% set version = '%s_%04i_%s'|format(GIT_DESCRIBE_TAG|replace('yosys-', '') or '0.X', GIT_DESCRIBE_NUMBER|int, GIT_DESCRIBE_HASH or 'gUNKNOWN') %}

package:
  name: yosys
  version: {{ version }}

source:
  git_url: https://github.com/timvideos/yosys.git
  git_rev: master
  patches:
    - makefile-conda-config.patch

build:
  # number: 201803050325
  number: {{ environ.get('DATE_NUM') }}
  # string: 20180305_0325
  string: {{ environ.get('DATE_STR') }}
  script_env:
    - CI
    - TRAVIS

requirements:
  build:
    - m2w64-toolchain [win]
    - m2-base [win]
    - m2-bash   [win]
    - m2-bison [win]
    - m2-flex [win]
    - python 3.6
    - tk
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - m2w64-toolchain [win]
    - m2-base [win]
    - m2-bison [win]
    - m2-flex [win]
    - m2-libreadline [win]
    - bison [not win]
    - flex [not win]
    - libffi [not win]
    - pkg-config [not win]
    - python 3.6
    - iverilog
  run:
    - python {{ python }}

about:
  home: http://www.clifford.at/yosys/
  license: ISC
  license_file: COPYING
  summary: 'Yosys is a framework for Verilog RTL synthesis. It currently has extensive Verilog-2005 support and provides a basic set of synthesis algorithms for various application domains.'
