language: shell

addons:
  homebrew:
    packages:
    update: false

osx_image:
  - xcode8.3
dist:
  - xenial

jobs:
  include:
 # Libraries
   # Linux
   - os: linux
     env:
     - PACKAGE=lib/isl
   - os: linux
     env:
     - PACKAGE=lib/usb
#  -  os: linux
#     env:
#     - PACKAGE=lib/ftdi
   # OSX
   - os: osx
     env:
     - PACKAGE=lib/isl
   - os: osx
     env:
     - PACKAGE=lib/usb
   - os: osx
     env:
     - PACKAGE=lib/ftdi
   # Windows
   - os: windows
     env:
     - PACKAGE=lib/usb
   - os: windows
     env:
     - PACKAGE=lib/ftdi
 # or1k toolchain
   - os: linux
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=or1k
   - os: linux
     env:
     - PACKAGE=gcc/nostdc   TOOLCHAIN_ARCH=or1k
   - os: linux
     env:
     - PACKAGE=gcc/newlib   TOOLCHAIN_ARCH=or1k
   - os: linux
     env:
     - PACKAGE=gcc/linux-musl TOOLCHAIN_ARCH=or1k
   - os: linux
     env:
     - PACKAGE=gdb          TOOLCHAIN_ARCH=or1k
   # OSX
   - os: osx
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=or1k
 # rv32 toolchain
   - os: linux
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=riscv32
   - os: linux
     env:
     - PACKAGE=gcc/nostdc   TOOLCHAIN_ARCH=riscv32
   - os: linux
     env:
     - PACKAGE=gcc/newlib   TOOLCHAIN_ARCH=riscv32
   - os: linux
     env:
     - PACKAGE=gcc/linux-musl TOOLCHAIN_ARCH=riscv32
   - os: linux
     env:
     - PACKAGE=gdb          TOOLCHAIN_ARCH=riscv32
   # OSX
   - os: osx
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=riscv32
 # rv64 toolchain
   - os: linux
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=riscv64
   - os: linux
     env:
     - PACKAGE=gcc/nostdc   TOOLCHAIN_ARCH=riscv64
   - os: linux
     env:
     - PACKAGE=gcc/newlib   TOOLCHAIN_ARCH=riscv64
   - os: linux
     env:
     - PACKAGE=gcc/linux-musl TOOLCHAIN_ARCH=riscv64
   - os: linux
     env:
     - PACKAGE=gdb          TOOLCHAIN_ARCH=riscv64
   # OSX
   - os: osx
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=riscv64
 # lm32 toolchain - no linux
   - os: linux
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=lm32
   - os: linux
     env:
     - PACKAGE=gcc/nostdc   TOOLCHAIN_ARCH=lm32
   - os: linux
     env:
     - PACKAGE=gcc/newlib   TOOLCHAIN_ARCH=lm32
   - os: linux
     env:
     - PACKAGE=gdb          TOOLCHAIN_ARCH=lm32
   # OSX
   - os: osx
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=lm32
 # ppc64le toolchain
   - os: linux
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=ppc64le
   - os: linux
     env:
     - PACKAGE=gcc/linux-musl TOOLCHAIN_ARCH=ppc64le
   # OSX
   - os: osx
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=ppc64le
 # sh toolchain
   - os: linux
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=sh
   - os: linux
     env:
     - PACKAGE=gcc/nostdc   TOOLCHAIN_ARCH=sh
   - os: linux
     env:
     - PACKAGE=gcc/newlib   TOOLCHAIN_ARCH=sh
   - os: linux
     env:
     - PACKAGE=gcc/linux-musl TOOLCHAIN_ARCH=sh
   - os: linux
     env:
     - PACKAGE=gdb          TOOLCHAIN_ARCH=sh
   # OSX
   - os: osx
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=sh
 # Full Linux musl toolchain using musl-cross-make
   - os: linux
     env:
     - PACKAGE=toolchain/linux-musl TOOLCHAIN_ARCH=or1k
   - os: linux
     env:
     - PACKAGE=toolchain/linux-musl TOOLCHAIN_ARCH=riscv32
   - os: linux
     env:
     - PACKAGE=toolchain/linux-musl TOOLCHAIN_ARCH=riscv64
   - os: linux
     env:
     - PACKAGE=toolchain/linux-musl TOOLCHAIN_ARCH=sh
 # Other tools
   # Linux
   - os: linux
     env:
     - PACKAGE=sdcc
   - os: linux
     dist: xenial
     env:
     - PACKAGE=sigrok-cli                 CONDA_CHANNELS=conda-forge
   - os: linux
     dist: xenial
     env:
     - PACKAGE=dtc
   # OSX
   - os: osx
     env:
     - PACKAGE=sdcc
 # Programming Tools
   # Linux
   - os: linux
     env:
     - PACKAGE=prog/iceprog
   - os: linux
     env:
     - PACKAGE=prog/icefunprog
   - os: linux
     env:
     - PACKAGE=prog/openocd
   - os: linux
     env:
     - PACKAGE=prog/fxload
   - os: linux
     env:
     - PACKAGE=prog/dfu-util
   # Windows
   - os: windows
     env:
     - PACKAGE=prog/iceprog
   # OSX
   - os: osx
     env:
     - PACKAGE=prog/iceprog
   - os: osx
     env:
     - PACKAGE=prog/icefunprog
   - os: osx
     env:
     - PACKAGE=prog/dfu-util
   - os: osx
     env:
     - PACKAGE=prog/openocd
 # Miscellaneus
   # Linux
   - os: linux
     env:
     - PACKAGE=misc/flterm
   # OSX
   - os: osx
     env:
     - PACKAGE=misc/flterm
 # EDA Tools - Bitstream Tools
   # Linux
   - os: linux
     env:
     - PACKAGE=eda/bit/icestorm
   - os: linux
     env:
     - PACKAGE=eda/bit/prjtrellis
   # Windows
   - os: windows
     env:
     - PACKAGE=eda/bit/icestorm
   - os: windows
     env:
     - PACKAGE=eda/bit/prjtrellis
   # OSX
   - os: osx
     env:
     - PACKAGE=eda/bit/icestorm
 # EDA Tools - Synthesis
   # Linux
   - os: linux
     env:
     - PACKAGE=eda/syn/yosys
   # Windows
   - os: windows
     env:
     - PACKAGE=eda/syn/yosys
   # OSX
   - os: osx
     env:
     - PACKAGE=eda/syn/yosys EXTRA_BUILD_ARGS="--no-test"
 # EDA Tools - Place and Route
   # Linux
   - os: linux
     env:
     - PACKAGE=eda/pnr/arachne
   - os: linux
     env:
     - PACKAGE=eda/pnr/nextpnr/ice40
   - os: linux
     env:
     - PACKAGE=eda/pnr/nextpnr/ecp5
   - os: linux
     env:
     - PACKAGE=eda/pnr/nextpnr/generic
#  - os: linux
#    dist: xenial
#    env:
#    - PACKAGE=eda/pnr/vtr                 CONDA_CHANNELS=conda-forge
   # Windows
   - os: windows
     env:
     - PACKAGE=eda/pnr/nextpnr/ice40
   # OSX
   - os: osx
     env:
     - PACKAGE=eda/pnr/nextpnr/ice40
 # EDA Tools - Simulation
   # Linux
   - os: linux
     env:
     - PACKAGE=eda/sim/icarus
   - os: linux
     env:
     - PACKAGE=eda/sim/verilator
   # Windows
   - os: windows
     env:
     - PACKAGE=eda/sim/icarus
   # OSX
   - os: osx
     env:
     - PACKAGE=eda/sim/icarus

  allow_failures:
   - env: PACKAGE=vtr CONDA_CHANNELS=conda-forge
  fast_finish: true

before_install:
 - source $TRAVIS_BUILD_DIR/.travis/common.sh
 - bash $TRAVIS_BUILD_DIR/.travis/fixup-git.sh
 - bash $TRAVIS_BUILD_DIR/.travis/download_sdk.sh
 - source $TRAVIS_BUILD_DIR/.travis/common.sh

install:
 - ./.travis/install.sh

script:
 - bash $TRAVIS_BUILD_DIR/.travis/script.sh

after_failure:
 - bash $TRAVIS_BUILD_DIR/.travis/after_failure.sh

after_success:
 - bash $TRAVIS_BUILD_DIR/.travis/after_success.sh

cache:
  directories:
   - $HOME/.conda/pkgs
