language: minimal

dist: xenial
addons:
  apt:
    packages:
    - realpath

jobs:
  include:
   # Libraries
   #- stage: "Libraries"
   #  env:
   #  - PACKAGE=lib/isl

   #- stage: "Libraries"
   #  env:
   #  - PACKAGE=lib/usb

   #- stage: "Libraries"
   #  env:
   #  - PACKAGE=lib/ftdi

   ## or1k toolchain
   #- stage: "Toolchain - Linux (musl)(GCC/Binutils/Activation scripts)"
   #  env:
   #  - PACKAGE=toolchain-ctng/linux-musl/or1k/recipe
   #  - EXTRA_PACKAGE=toolchain-ctng/linux-musl/or1k/activation_scripts
   #  - CUSTOM_BUILD_SCRIPT=toolchain-ctng/build_toolchain.sh
   #  - TRAVIS_WAIT_TIME=50
   #- stage: "Toolchain - newlib (GCC/Binutils/Activation scripts)"
   #  env:
   #  - PACKAGE=toolchain-ctng/newlib/or1k/recipe
   #  - EXTRA_PACKAGE=toolchain-ctng/newlib/or1k/activation_scripts
   #  - CUSTOM_BUILD_SCRIPT=toolchain-ctng/build_toolchain.sh
   #  - TRAVIS_WAIT_TIME=50
   - stage: "Toolchain - nostdc (stage 1) (GCC/Binutils)"
     env:
     - PACKAGE=toolchain-ctng/binaries
     - CUSTOM_BUILD_SCRIPT="toolchain-ctng/build-scripts/or1k-elf-nostdc.sh"
     - TRAVIS_WAIT_TIME=50
   - stage: "Toolchain - nostdc (stage 2) (Activation scripts)"
     env:
     - PACKAGE=toolchain-ctng/activation_scripts
     - CUSTOM_BUILD_SCRIPT="toolchain-ctng/build-scripts/or1k-elf-nostdc.sh"
       #- stage: "GDB"
       #  env:
       #  - PACKAGE=toolchain-ctng/recipe

       ## rv32 toolchain
       #- stage: "Toolchain - Linux (musl)(GCC/Binutils/Activation scripts)"
       #  env:
       #  - PACKAGE=toolchain-ctng/linux-musl/riscv32/recipe
       #  - EXTRA_PACKAGE=toolchain-ctng/linux-musl/riscv32/activation_scripts
       #  - CUSTOM_BUILD_SCRIPT=toolchain-ctng/build_toolchain.sh
       #  - TRAVIS_WAIT_TIME=50
       #- stage: "Toolchain - newlib (GCC/Binutils/Activation scripts)"
       #  env:
       #  - PACKAGE=toolchain-ctng/newlib/riscv32/recipe
       #  - EXTRA_PACKAGE=toolchain-ctng/newlib/riscv32/activation_scripts
       #  - CUSTOM_BUILD_SCRIPT=toolchain-ctng/build_toolchain.sh
       #  - TRAVIS_WAIT_TIME=50
       #- stage: "Toolchain - nostdc (musl)(GCC/Binutils/Activation scripts)"
       #  env:
       #  - PACKAGE=toolchain-ctng/nostdc/riscv32/recipe
       #  - EXTRA_PACKAGE=toolchain-ctng/nostdc/riscv32/activation_scripts
       #  - CUSTOM_BUILD_SCRIPT=toolchain-ctng/build_toolchain.sh
       #  - TRAVIS_WAIT_TIME=50
       #- stage: "GDB"
       #  env:
       #  - PACKAGE=toolchain-ctng/recipe

       ## rv64 toolchain
       #- stage: "Binutils"
       #  env:
       #  - PACKAGE=binutils     TOOLCHAIN_ARCH=riscv64
       #- stage: "GCC - nostdc"
       #  env:
       #  - PACKAGE=gcc/nostdc   TOOLCHAIN_ARCH=riscv64
       #- stage: "GCC - newlib"
       #  env:
       #  - PACKAGE=gcc/newlib   TOOLCHAIN_ARCH=riscv64
       #- stage: "GCC - Linux (musl)"
       #  env:
       #  - PACKAGE=gcc/linux-musl TOOLCHAIN_ARCH=riscv64
       #- stage: "GDB"
       #  env:
       #  - PACKAGE=gdb          TOOLCHAIN_ARCH=riscv64

       ## lm32 toolchain - no linux
       #- stage: "Toolchain - newlib (GCC/Binutils/Activation scripts)"
       #  env:
       #  - PACKAGE=toolchain-ctng/newlib/lm32/recipe
       #  - EXTRA_PACKAGE=toolchain-ctng/newlib/lm32/activation_scripts
       #  - CUSTOM_BUILD_SCRIPT=toolchain-ctng/build_toolchain.sh
       #  - TRAVIS_WAIT_TIME=50
       #- stage: "Toolchain - nostdc (musl)(GCC/Binutils/Activation scripts)"
       #  env:
       #  - PACKAGE=toolchain-ctng/nostdc/lm32/recipe
       #  - EXTRA_PACKAGE=toolchain-ctng/nostdc/lm32/activation_scripts
       #  - CUSTOM_BUILD_SCRIPT=toolchain-ctng/build_toolchain.sh
       #  - TRAVIS_WAIT_TIME=50
       #- stage: "GDB"
       #  env:
       #  - PACKAGE=gdb          TOOLCHAIN_ARCH=lm32

       ## ppc64le toolchain
       #- stage: "Binutils"
       #  env:
       #  - PACKAGE=binutils     TOOLCHAIN_ARCH=ppc64le
#      # - stage: "GCC - nostdc"
#      #   env:
#      #   - PACKAGE=gcc/nostdc   TOOLCHAIN_ARCH=ppc64le
#      # - stage: "GCC - newlib"
#      #   env:
#      #   - PACKAGE=gcc/newlib   TOOLCHAIN_ARCH=ppc64le
       #- stage: "GCC - Linux (musl)"
       #  env:
       #  - PACKAGE=gcc/linux-musl TOOLCHAIN_ARCH=ppc64le
#      # - stage: "GDB"
#      #   env:
#      #   - PACKAGE=gdb          TOOLCHAIN_ARCH=ppc64le

       ## sh2 toolchain
       #- stage: "Binutils"
       #  env:
       #  - PACKAGE=binutils     TOOLCHAIN_ARCH=sh
       #- stage: "GCC - nostdc"
       #  env:
       #  - PACKAGE=gcc/nostdc   TOOLCHAIN_ARCH=sh
       #- stage: "GCC - newlib"
       #  env:
       #  - PACKAGE=gcc/newlib   TOOLCHAIN_ARCH=sh
       #- stage: "GCC - Linux (musl)"
       #  env:
       #  - PACKAGE=gcc/linux-musl TOOLCHAIN_ARCH=sh
       #- stage: "GDB"
       #  env:
       #  - PACKAGE=gdb          TOOLCHAIN_ARCH=sh

       ## Full Linux musl toolchain using musl-cross-make
       #- stage: "Toolchain - Linux MUSL"
       #  env:
       #  - PACKAGE=toolchain/linux-musl TOOLCHAIN_ARCH=riscv64
#      # - stage: "Toolchain - Linux MUSL"
#      #   env:
#      #   - PACKAGE=toolchain/linux-musl TOOLCHAIN_ARCH=ppc64le
       #- stage: "Toolchain - Linux MUSL"
       #  env:
       #  - PACKAGE=toolchain/linux-musl TOOLCHAIN_ARCH=sh

       ## Other tools
       #- stage: "Other Tools"
       #  env:
       #  - PACKAGE=sdcc

       ## Programming Tools
       #- stage: "Programming Tools"
       #  env:
       #  - PACKAGE=prog/iceprog

       #- stage: "Programming Tools"
       #  env:
       #  - PACKAGE=prog/icefunprog

       #- stage: "Programming Tools"
       #  env:
       #  - PACKAGE=prog/openocd

       #- stage: "Programming Tools"
       #  env:
       #  - PACKAGE=prog/flterm

       #- stage: "Programming Tools"
       #  env:
       #  - PACKAGE=prog/fxload

       #- stage: "Programming Tools"
       #  env:
       #  - PACKAGE=prog/dfu-util

       ## EDA Tools - Bitstream Tool
       #- stage: "EDA Tools"
       #  env:
       #  - PACKAGE=eda/bit/icestorm

       #- stage: "EDA Tools"
       #  env:
       #  - PACKAGE=eda/bit/prjtrellis

       ## EDA Tools - Synthesis
       #- stage: "EDA Tools"
       #  env:
       #  - PACKAGE=eda/syn/yosys

       ## EDA Tools - Place and Route
       #- stage: "EDA Tools"
       #  env:
       #  - PACKAGE=eda/pnr/arachne

       #- stage: "EDA Tools"
       #  env:
       #  - PACKAGE=eda/pnr/nextpnr/ice40

       #- stage: "EDA Tools"
       #  env:
       #  - PACKAGE=eda/pnr/nextpnr/ecp5

       #- stage: "EDA Tools"
       #  env:
       #  - PACKAGE=eda/pnr/nextpnr/generic

#      # - stage: "EDA Tools"
#      #   env:
#      #   - PACKAGE=eda/pnr/vtr                 CONDA_CHANNELS=conda-forge

       ## EDA Tools - Simulation
       #- stage: "EDA Tools"
       #  env:
       #  - PACKAGE=eda/sim/icarus

       #- stage: "EDA Tools"
       #  env:
       #  - PACKAGE=eda/sim/verilator

before_install:
 - source $TRAVIS_BUILD_DIR/.travis/common.sh
 - bash $TRAVIS_BUILD_DIR/.travis/fixup-git.sh
 - source $TRAVIS_BUILD_DIR/.travis/common.sh

install:
 - ./.travis/install.sh

script:
 - bash $TRAVIS_BUILD_DIR/.travis/script.sh

after_failure:
 - bash $TRAVIS_BUILD_DIR/.travis/after_failure.sh

after_success:
 - bash $TRAVIS_BUILD_DIR/.travis/after_success.sh

cache:
  directories:
   - /home/travis/.conda/pkgs
