language: minimal

os:
  - linux
    dist: xenial
  - windows
addons:
  apt:
    packages:
    - realpath

jobs:
  include:
   # Libraries
   - stage: "Libraries"
     env:
     - PACKAGE=lib/isl

   - stage: "Libraries"
     env:
     - PACKAGE=lib/usb

   - stage: "Libraries"
     env:
     - PACKAGE=lib/ftdi

   # or1k toolchain
   - stage: "Binutils"
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=or1k
   - stage: "GCC - nostdc"
     env:
     - PACKAGE=gcc/nostdc   TOOLCHAIN_ARCH=or1k
   - stage: "GCC - newlib"
     env:
     - PACKAGE=gcc/newlib   TOOLCHAIN_ARCH=or1k
   - stage: "GCC - Linux (musl)"
     env:
     - PACKAGE=gcc/linux-musl TOOLCHAIN_ARCH=or1k
   - stage: "GDB"
     env:
     - PACKAGE=gdb          TOOLCHAIN_ARCH=or1k

   # rv32 toolchain
   - stage: "Binutils"
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=riscv32
   - stage: "GCC - nostdc"
     env:
     - PACKAGE=gcc/nostdc   TOOLCHAIN_ARCH=riscv32
   - stage: "GCC - newlib"
     env:
     - PACKAGE=gcc/newlib   TOOLCHAIN_ARCH=riscv32
   - stage: "GCC - Linux (musl)"
     env:
     - PACKAGE=gcc/linux-musl TOOLCHAIN_ARCH=riscv32
   - stage: "GDB"
     env:
     - PACKAGE=gdb          TOOLCHAIN_ARCH=riscv32

   # rv64 toolchain
   - stage: "Binutils"
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=riscv64
   - stage: "GCC - nostdc"
     env:
     - PACKAGE=gcc/nostdc   TOOLCHAIN_ARCH=riscv64
   - stage: "GCC - newlib"
     env:
     - PACKAGE=gcc/newlib   TOOLCHAIN_ARCH=riscv64
   - stage: "GCC - Linux (musl)"
     env:
     - PACKAGE=gcc/linux-musl TOOLCHAIN_ARCH=riscv64
   - stage: "GDB"
     env:
     - PACKAGE=gdb          TOOLCHAIN_ARCH=riscv64

   # lm32 toolchain - no linux
   - stage: "Binutils"
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=lm32
   - stage: "GCC - nostdc"
     env:
     - PACKAGE=gcc/nostdc   TOOLCHAIN_ARCH=lm32
   - stage: "GCC - newlib"
     env:
     - PACKAGE=gcc/newlib   TOOLCHAIN_ARCH=lm32
   - stage: "GDB"
     env:
     - PACKAGE=gdb          TOOLCHAIN_ARCH=lm32

   # ppc64le toolchain
   - stage: "Binutils"
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=ppc64le
#   - stage: "GCC - nostdc"
#     env:
#     - PACKAGE=gcc/nostdc   TOOLCHAIN_ARCH=ppc64le
#   - stage: "GCC - newlib"
#     env:
#     - PACKAGE=gcc/newlib   TOOLCHAIN_ARCH=ppc64le
   - stage: "GCC - Linux (musl)"
     env:
     - PACKAGE=gcc/linux-musl TOOLCHAIN_ARCH=ppc64le
#   - stage: "GDB"
#     env:
#     - PACKAGE=gdb          TOOLCHAIN_ARCH=ppc64le

   # sh2 toolchain
   - stage: "Binutils"
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=sh
   - stage: "GCC - nostdc"
     env:
     - PACKAGE=gcc/nostdc   TOOLCHAIN_ARCH=sh
   - stage: "GCC - newlib"
     env:
     - PACKAGE=gcc/newlib   TOOLCHAIN_ARCH=sh
   - stage: "GCC - Linux (musl)"
     env:
     - PACKAGE=gcc/linux-musl TOOLCHAIN_ARCH=sh
   - stage: "GDB"
     env:
     - PACKAGE=gdb          TOOLCHAIN_ARCH=sh

   # Full Linux musl toolchain using musl-cross-make
   - stage: "Toolchain - Linux MUSL"
     env:
     - PACKAGE=toolchain/linux-musl TOOLCHAIN_ARCH=or1k
   - stage: "Toolchain - Linux MUSL"
     env:
     - PACKAGE=toolchain/linux-musl TOOLCHAIN_ARCH=riscv32
   - stage: "Toolchain - Linux MUSL"
     env:
     - PACKAGE=toolchain/linux-musl TOOLCHAIN_ARCH=riscv64
#   - stage: "Toolchain - Linux MUSL"
#     env:
#     - PACKAGE=toolchain/linux-musl TOOLCHAIN_ARCH=ppc64le
   - stage: "Toolchain - Linux MUSL"
     env:
     - PACKAGE=toolchain/linux-musl TOOLCHAIN_ARCH=sh

   # Other tools
   - stage: "Other Tools"
     env:
     - PACKAGE=sdcc

   # Programming Tools
   - stage: "Programming Tools"
     env:
     - PACKAGE=prog/iceprog

   - stage: "Programming Tools"
     env:
     - PACKAGE=prog/icefunprog

   - stage: "Programming Tools"
     env:
     - PACKAGE=prog/openocd

   - stage: "Programming Tools"
     env:
     - PACKAGE=prog/flterm

   - stage: "Programming Tools"
     env:
     - PACKAGE=prog/fxload

   - stage: "Programming Tools"
     env:
     - PACKAGE=prog/dfu-util

   # EDA Tools - Bitstream Tool
   - stage: "EDA Tools"
     env:
     - PACKAGE=eda/bit/icestorm

   - stage: "EDA Tools"
     env:
     - PACKAGE=eda/bit/prjtrellis

   # EDA Tools - Synthesis
   - stage: "EDA Tools"
     env:
     - PACKAGE=eda/syn/yosys

   # EDA Tools - Place and Route
   - stage: "EDA Tools"
     env:
     - PACKAGE=eda/pnr/arachne

   - stage: "EDA Tools"
     env:
     - PACKAGE=eda/pnr/nextpnr/ice40

   - stage: "EDA Tools"
     env:
     - PACKAGE=eda/pnr/nextpnr/ecp5

   - stage: "EDA Tools"
     env:
     - PACKAGE=eda/pnr/nextpnr/generic

#   - stage: "EDA Tools"
#     env:
#     - PACKAGE=eda/pnr/vtr                 CONDA_CHANNELS=conda-forge

   # EDA Tools - Simulation
   - stage: "EDA Tools"
     env:
     - PACKAGE=eda/sim/icarus

   - stage: "EDA Tools"
     env:
     - PACKAGE=eda/sim/verilator

  exclude:
   # Exclude builds on windows
   # Libraries
   - os: windows
     env:
     - PACKAGE=lib/isl
   # or1k toolchain
   - os: windows
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=or1k
   - os: windows
     env:
     - PACKAGE=gcc/nostdc   TOOLCHAIN_ARCH=or1k
   - os: windows
     env:
     - PACKAGE=gcc/newlib   TOOLCHAIN_ARCH=or1k
   - os: windows
     env:
     - PACKAGE=gcc/linux-musl TOOLCHAIN_ARCH=or1k
   - os: windows
     env:
     - PACKAGE=gdb          TOOLCHAIN_ARCH=or1k
   # rv32 toolchain
   - os: windows
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=riscv32
   - os: windows
     env:
     - PACKAGE=gcc/nostdc   TOOLCHAIN_ARCH=riscv32
   - os: windows
     env:
     - PACKAGE=gcc/newlib   TOOLCHAIN_ARCH=riscv32
   - os: windows
     env:
     - PACKAGE=gcc/linux-musl TOOLCHAIN_ARCH=riscv32
   - os: windows
     env:
     - PACKAGE=gdb          TOOLCHAIN_ARCH=riscv32
   # rv64 toolchain
   - os: windows
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=riscv64
   - os: windows
     env:
     - PACKAGE=gcc/nostdc   TOOLCHAIN_ARCH=riscv64
   - os: windows
     env:
     - PACKAGE=gcc/newlib   TOOLCHAIN_ARCH=riscv64
   - os: windows
     env:
     - PACKAGE=gcc/linux-musl TOOLCHAIN_ARCH=riscv64
   - os: windows
     env:
     - PACKAGE=gdb          TOOLCHAIN_ARCH=riscv64
   # lm32 toolchain - no linux
   - os: windows
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=lm32
   - os: windows
     env:
     - PACKAGE=gcc/nostdc   TOOLCHAIN_ARCH=lm32
   - os: windows
     env:
     - PACKAGE=gcc/newlib   TOOLCHAIN_ARCH=lm32
   - os: windows
     env:
     - PACKAGE=gdb          TOOLCHAIN_ARCH=lm32
   # ppc64le toolchain
   - os: windows
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=ppc64le
#   - os: windows
#     env:
#     - PACKAGE=gcc/nostdc   TOOLCHAIN_ARCH=ppc64le
#   - os: windows
#     env:
#     - PACKAGE=gcc/newlib   TOOLCHAIN_ARCH=ppc64le
   - os: windows
     env:
     - PACKAGE=gcc/linux-musl TOOLCHAIN_ARCH=ppc64le
#   - os: windows
#     env:
#     - PACKAGE=gdb          TOOLCHAIN_ARCH=ppc64le
   # sh2 toolchain
   - os: windows
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=sh
   - os: windows
     env:
     - PACKAGE=gcc/nostdc   TOOLCHAIN_ARCH=sh
   - os: windows
     env:
     - PACKAGE=gcc/newlib   TOOLCHAIN_ARCH=sh
   - os: windows
     env:
     - PACKAGE=gcc/linux-musl TOOLCHAIN_ARCH=sh
   - os: windows
     env:
     - PACKAGE=gdb          TOOLCHAIN_ARCH=sh
   # Full Linux musl toolchain using musl-cross-make
   - os: windows
     env:
     - PACKAGE=toolchain/linux-musl TOOLCHAIN_ARCH=or1k
   - os: windows
     env:
     - PACKAGE=toolchain/linux-musl TOOLCHAIN_ARCH=riscv32
   - os: windows
     env:
     - PACKAGE=toolchain/linux-musl TOOLCHAIN_ARCH=riscv64
#   - os: windows
#     env:
#     - PACKAGE=toolchain/linux-musl TOOLCHAIN_ARCH=ppc64le
   - os: windows
     env:
     - PACKAGE=toolchain/linux-musl TOOLCHAIN_ARCH=sh
   # Other tools
   - os: windows
     env:
     - PACKAGE=sdcc
   # Programming Tools
   - os: windows
     env:
     - PACKAGE=prog/iceprog
   - os: windows
     env:
     - PACKAGE=prog/icefunprog
   - os: windows
     env:
     - PACKAGE=prog/openocd
   - os: windows
     env:
     - PACKAGE=prog/flterm
   - os: windows
     env:
     - PACKAGE=prog/fxload
   - os: windows
     env:
     - PACKAGE=prog/dfu-util
   # EDA Tools - Bitstream Tool
   - os: windows
     env:
     - PACKAGE=eda/bit/prjtrellis
   # EDA Tools - Synthesis
   - os: windows
     env:
     - PACKAGE=eda/syn/yosys
   # EDA Tools - Place and Route
   - os: windows
     env:
     - PACKAGE=eda/pnr/arachne
   - os: windows
     env:
     - PACKAGE=eda/pnr/nextpnr/ice40
   - os: windows
     env:
     - PACKAGE=eda/pnr/nextpnr/ecp5
   - os: windows
     env:
     - PACKAGE=eda/pnr/nextpnr/generic
#   - os: windows
#     env:
#     - PACKAGE=eda/pnr/vtr                 CONDA_CHANNELS=conda-forge
   # EDA Tools - Simulation
   - os: windows
     env:
     - PACKAGE=eda/sim/verilator

matrix:
  allow_failures:
  - env: PACKAGE=vtr CONDA_CHANNELS=conda-forge
  fast_finish: true

before_install:
 - source $TRAVIS_BUILD_DIR/.travis/common.sh
 - bash $TRAVIS_BUILD_DIR/.travis/fixup-git.sh
 - source $TRAVIS_BUILD_DIR/.travis/common.sh

install:
 - ./.travis/install.sh

script:
 - bash $TRAVIS_BUILD_DIR/.travis/script.sh

after_failure:
 - bash $TRAVIS_BUILD_DIR/.travis/after_failure.sh

after_success:
 - bash $TRAVIS_BUILD_DIR/.travis/after_success.sh

cache:
  directories:
   - /home/travis/.conda/pkgs
