language: shell

addons:
  homebrew:
    packages:
    update: false

dist:
  - xenial

stages:
  - "Libraries"
  - "Binutils"
  - "GCC - nostdc"
  - "GCC - newlib"
  - "GCC - Linux (musl)"
  - "GDB"
  - "Toolchain - linux musl"
  - "Other tools"
  - "Programming tools"
  - "Miscellaneus"
  - "EDA Tools - bitstream"
  - "Eda tools"

jobs:
  include:
 # Libraries
   # Linux
   - stage: "Libraries"
     os: linux
     env:
     - PACKAGE=lib/isl
   - stage: "Libraries"
     os: linux
     env:
     - PACKAGE=lib/usb
#  - stage: "Libraries"
#     os: linux
#     env:
#     - PACKAGE=lib/ftdi
   # OSX
   - stage: "Libraries"
     os: osx
     osx_image: xcode8.3
     env:
     - PACKAGE=lib/isl
   - stage: "Libraries"
     os: osx
     osx_image: xcode8.3
     env:
     - PACKAGE=lib/usb
   - stage: "Libraries"
     os: osx
     osx_image: xcode8.3
     env:
     - PACKAGE=lib/ftdi
   # Windows
   - stage: "Libraries"
     os: windows
     env:
     - PACKAGE=lib/usb
   - stage: "Libraries"
     os: windows
     env:
     - PACKAGE=lib/ftdi
 # or1k toolchain
   - stage: "Binutils"
     os: linux
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=or1k
   - stage: "GCC - nostdc"
     os: linux
     env:
     - PACKAGE=gcc/nostdc   TOOLCHAIN_ARCH=or1k
   - stage: "GCC - newlib"
     os: linux
     env:
     - PACKAGE=gcc/newlib   TOOLCHAIN_ARCH=or1k
   - stage: "GCC - Linux (musl)"
     os: linux
     env:
     - PACKAGE=gcc/linux-musl TOOLCHAIN_ARCH=or1k
   - stage: "GDB"
     os: linux
     env:
     - PACKAGE=gdb          TOOLCHAIN_ARCH=or1k
   # OSX
   - stage: "Binutils"
     os: osx
     osx_image: xcode8.3
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=or1k
 # rv32 toolchain
   - stage: "Binutils"
     os: linux
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=riscv32
   - stage: "GCC - nostdc"
     os: linux
     env:
     - PACKAGE=gcc/nostdc   TOOLCHAIN_ARCH=riscv32
   - stage: "GCC - newlib"
     os: linux
     env:
     - PACKAGE=gcc/newlib   TOOLCHAIN_ARCH=riscv32
   - stage: "GCC - Linux (musl)"
     os: linux
     env:
     - PACKAGE=gcc/linux-musl TOOLCHAIN_ARCH=riscv32
   - stage: "GDB"
     os: linux
     env:
     - PACKAGE=gdb          TOOLCHAIN_ARCH=riscv32
   # OSX
   - stage: "Binutils"
     os: osx
     osx_image: xcode8.3
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=riscv32
 # rv64 toolchain
   - stage: "Binutils"
     os: linux
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=riscv64
   - stage: "GCC - nostdc"
     os: linux
     env:
     - PACKAGE=gcc/nostdc   TOOLCHAIN_ARCH=riscv64
   - stage: "GCC - newlib"
     os: linux
     env:
     - PACKAGE=gcc/newlib   TOOLCHAIN_ARCH=riscv64
   - stage: "GCC - Linux (musl)"
     os: linux
     env:
     - PACKAGE=gcc/linux-musl TOOLCHAIN_ARCH=riscv64
   - stage: "GDB"
     os: linux
     env:
     - PACKAGE=gdb          TOOLCHAIN_ARCH=riscv64
   # OSX
   - stage: "Binutils"
     os: osx
     osx_image: xcode8.3
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=riscv64
 # lm32 toolchain - no linux
   - stage: "Binutils"
     os: linux
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=lm32
   - stage: "GCC - nostdc"
     os: linux
     env:
     - PACKAGE=gcc/nostdc   TOOLCHAIN_ARCH=lm32
   - stage: "GCC - newlib"
     os: linux
     env:
     - PACKAGE=gcc/newlib   TOOLCHAIN_ARCH=lm32
   - stage: "GDB"
     os: linux
     env:
     - PACKAGE=gdb          TOOLCHAIN_ARCH=lm32
   # OSX
   - stage: "Binutils"
     os: osx
     osx_image: xcode8.3
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=lm32
 # ppc64le toolchain
   - stage: "Binutils"
     os: linux
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=ppc64le
   - stage: "GCC - Linux (musl)"
     os: linux
     env:
     - PACKAGE=gcc/linux-musl TOOLCHAIN_ARCH=ppc64le
   # OSX
   - stage: "Binutils"
     os: osx
     osx_image: xcode8.3
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=ppc64le
 # sh toolchain
   - stage: "Binutils"
     os: linux
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=sh
   - stage: "GCC - nostdc"
     os: linux
     env:
     - PACKAGE=gcc/nostdc   TOOLCHAIN_ARCH=sh
   - stage: "GCC - newlib"
     os: linux
     env:
     - PACKAGE=gcc/newlib   TOOLCHAIN_ARCH=sh
   - stage: "GCC - Linux (musl)"
     os: linux
     env:
     - PACKAGE=gcc/linux-musl TOOLCHAIN_ARCH=sh
   - stage: "GDB"
     os: linux
     env:
     - PACKAGE=gdb          TOOLCHAIN_ARCH=sh
   # OSX
   - stage: "Binutils"
     os: osx
     osx_image: xcode8.3
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=sh
 # Full Linux musl toolchain using musl-cross-make
   - stage: "Toolchain - Linux MUSL"
     os: linux
     env:
     - PACKAGE=toolchain/linux-musl TOOLCHAIN_ARCH=or1k
   - stage: "Toolchain - Linux MUSL"
     os: linux
     env:
     - PACKAGE=toolchain/linux-musl TOOLCHAIN_ARCH=riscv32
   - stage: "Toolchain - Linux MUSL"
     os: linux
     env:
     - PACKAGE=toolchain/linux-musl TOOLCHAIN_ARCH=riscv64
   - stage: "Toolchain - Linux MUSL"
     os: linux
     env:
     - PACKAGE=toolchain/linux-musl TOOLCHAIN_ARCH=sh
 # Other tools
   # Linux
   - stage: "Other Tools"
     os: linux
     env:
     - PACKAGE=sdcc
   - stage: "Other Tools"
     os: linux
     dist: xenial
     env:
     - PACKAGE=sigrok-cli                 CONDA_CHANNELS=conda-forge
   - stage: "Other Tools"
     os: linux
     dist: xenial
     env:
     - PACKAGE=dtc
   # OSX
   - stage: "Other Tools"
     os: osx
     osx_image: xcode8.3
     env:
     - PACKAGE=sdcc
 # Programming Tools
   # Linux
   - stage: "Programming Tools"
     os: linux
     env:
     - PACKAGE=prog/iceprog
   - stage: "Programming Tools"
     os: linux
     env:
     - PACKAGE=prog/icefunprog
   - stage: "Programming Tools"
     os: linux
     env:
     - PACKAGE=prog/openocd
   - stage: "Programming Tools"
     os: linux
     env:
     - PACKAGE=prog/fxload
   - stage: "Programming Tools"
     os: linux
     env:
     - PACKAGE=prog/dfu-util
   # Windows
   - stage: "Programming Tools"
     os: windows
     env:
     - PACKAGE=prog/iceprog
   # OSX
   - stage: "Programming Tools"
     os: osx
     osx_image: xcode8.3
     env:
     - PACKAGE=prog/iceprog
   - stage: "Programming Tools"
     os: osx
     osx_image: xcode8.3
     env:
     - PACKAGE=prog/icefunprog
   - stage: "Programming Tools"
     os: osx
     osx_image: xcode8.3
     env:
     - PACKAGE=prog/dfu-util
   - stage: "Programming Tools"
     os: osx
     osx_image: xcode8.3
     env:
     - PACKAGE=prog/openocd
 # Miscellaneus
   # Linux
   - stage: "Miscellaneus"
     os: linux
     env:
     - PACKAGE=misc/flterm
   # OSX
   - stage: "Miscellaneus"
     os: osx
     osx_image: xcode8.3
     env:
     - PACKAGE=misc/flterm
 # EDA Tools - Bitstream Tools
   # Linux
   - stage: "EDA Tools - bitstream"
     os: linux
     env:
     - PACKAGE=eda/bit/icestorm
   - stage: "EDA Tools - bitstream"
     os: linux
     env:
     - PACKAGE=eda/bit/prjtrellis
   # Windows
   - stage: "EDA Tools"
     os: windows
     env:
     - PACKAGE=eda/bit/icestorm
   - stage: "EDA Tools"
     os: windows
     env:
     - PACKAGE=eda/bit/prjtrellis
   # OSX
   - stage: "EDA Tools"
     os: osx
     osx_image: xcode8.3
     env:
     - PACKAGE=eda/bit/icestorm
 # EDA Tools - Synthesis
   # Linux
   - stage: "EDA Tools"
     os: linux
     env:
     - PACKAGE=eda/syn/yosys
   # Windows
   - stage: "EDA Tools"
     os: windows
     env:
     - PACKAGE=eda/syn/yosys
   # OSX
   - stage: "EDA Tools"
     os: osx
     osx_image: xcode8.3
     env:
     - PACKAGE=eda/syn/yosys EXTRA_BUILD_ARGS="--no-test"
 # EDA Tools - Place and Route
   # Linux
   - stage: "EDA Tools"
     os: linux
     env:
     - PACKAGE=eda/pnr/arachne
   - stage: "EDA Tools"
     os: linux
     env:
     - PACKAGE=eda/pnr/nextpnr/ice40
   - stage: "EDA Tools"
     os: linux
     env:
     - PACKAGE=eda/pnr/nextpnr/ecp5
   - stage: "EDA Tools"
     os: linux
     env:
     - PACKAGE=eda/pnr/nextpnr/generic
#  - stage: "EDA Tools"
#    os: linux
#    dist: xenial
#    env:
#    - PACKAGE=eda/pnr/vtr                 CONDA_CHANNELS=conda-forge
   # Windows
   - stage: "EDA Tools"
     os: windows
     env:
     - PACKAGE=eda/pnr/nextpnr/ice40
   # OSX
   - stage: "EDA Tools"
     os: osx
     osx_image: xcode8.3
     env:
     - PACKAGE=eda/pnr/nextpnr/ice40
 # EDA Tools - Simulation
   # Linux
   - stage: "EDA Tools"
     os: linux
     env:
     - PACKAGE=eda/sim/icarus
   - stage: "EDA Tools"
     os: linux
     env:
     - PACKAGE=eda/sim/verilator
   # Windows
   - stage: "EDA Tools"
     os: windows
     env:
     - PACKAGE=eda/sim/icarus
   # OSX
   - stage: "EDA Tools"
     os: osx
     osx_image: xcode8.3
     env:
     - PACKAGE=eda/sim/icarus

  allow_failures:
   - env: PACKAGE=vtr CONDA_CHANNELS=conda-forge
  fast_finish: true

before_install:
 - source $TRAVIS_BUILD_DIR/.travis/common.sh
 - bash $TRAVIS_BUILD_DIR/.travis/fixup-git.sh
 - bash $TRAVIS_BUILD_DIR/.travis/download_sdk.sh
 - source $TRAVIS_BUILD_DIR/.travis/common.sh

install:
 - ./.travis/install.sh

script:
 - bash $TRAVIS_BUILD_DIR/.travis/script.sh

after_failure:
 - bash $TRAVIS_BUILD_DIR/.travis/after_failure.sh

after_success:
 - bash $TRAVIS_BUILD_DIR/.travis/after_success.sh

cache:
  directories:
   - $HOME/.conda/pkgs
