{% set version = '%s_%04i_%s'|format(GIT_DESCRIBE_TAG or 'sUNKNOWN', GIT_DESCRIBE_NUMBER|int, GIT_DESCRIBE_HASH or 'gUNKNOWN') %}

package:
  name: iverilog
  version: {{ version }}

source:
  git_url: https://github.com/steveicarus/iverilog.git
  git_rev: master
  patches:
    - fix-vvp-path.patch

build:
  # number: 201803050325
  number: {{ environ.get('DATE_NUM') }}
  # string: 20180305_0325
  string: {{ environ.get('DATE_STR') }}
  script_env:
    - CI
    - TRAVIS

requirements:
  build:
    - readline [not win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - gperf [not win]
    - bison [not win]
  run:
  {% for package in resolved_packages('host') %}
    - {{ package }}
  {% endfor %}
  {% for package in resolved_packages('build') %}
    - {{ package }}
  {% endfor %}

test:
  files:
    - test/fsm.v
    - test/counter.v
    - test/counter_tb.v
    - test/counter_list.txt
    - test/hello_world.v

about:
  home: http://iverilog.icarus.com/
  license: GPLv2
  license_file: COPYING
  summary: 'Icarus Verilog (iverilog) is a Verilog simulation and synthesis tool. It operates as a compiler, compiling source code written in Verilog (IEEE-1364) into some target format. For batch simulation, the compiler can generate an intermediate form called vvp assembly. This intermediate form is executed by the ``vvp'' command. For synthesis, the compiler generates netlists in the desired format.'
