{% set version = '%s_%04i_%s'|format(GIT_DESCRIBE_TAG|replace('v', '') or 'X.X', GIT_DESCRIBE_NUMBER|int, GIT_DESCRIBE_HASH or 'gUNKNOWN') %}

package:
  name: flterm
  version: {{ version }}

source:
  git_url: https://github.com/timvideos/flterm.git
  patches:
    - install_macos.patch

build:
  # number: 201803050325
  number: {{ environ.get('DATE_NUM') }}
  # string: 20180305_0325
  string: {{ environ.get('DATE_STR') }}
  script_env:
    - CI
    - TRAVIS

requirements:
  build:
    - {{ compiler('c') }}
    - vs2017_win-64    [win]
    - msys2:m2-make [win]
    - msys2:m2-base [win]
    - msys2:m2w64-toolchain [win]
  run:
  {% for package in resolved_packages('host') %}
    - {{ package }}
  {% endfor %}

test:
  commands:
    - flterm --help

about:
  home: https://github.com/timvideos/flterm
  license: GPLv3
  summary: 'Serial boot program for MiSoC'
