{% set version = '%s_%04i_%s'|format(GIT_DESCRIBE_TAG or 'v0.X', GIT_DESCRIBE_NUMBER|int, GIT_DESCRIBE_HASH or 'gUNKNOWN') %}

package:
  name: iceprog
  version: {{ version }}

source:
  git_url: https://github.com/mithro/icestorm.git
  git_rev: master
  patches:
   - iceprog-only.patch
   - win_build.patch [win]

build:
  # number: 201803050325
  number: {{ environ.get('DATE_NUM') }}
  # string: 20180305_0325
  string: {{ environ.get('DATE_STR') }}
  script_env:
    - CI
    - TRAVIS

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config [not win]
    - msys2:m2w64-toolchain [win]
    - msys:m2-base      [win]
    - msys2:m2-make              [win]
    - vs2017_win-64     [win]
    - libftdi
    - libusb
  host:
    - libftdi
    - libusb
  run:
    - icestorm
    - libftdi

about:
  home: http://www.clifford.at/icestorm/
  license_file: COPYING
  summary: 'Project IceStorm aims at documenting the bitstream format of Lattice iCE40 FPGAs and providing simple tools for analyzing and creating bitstream files.'

extra:
  maintainers:
    - Tim 'mithro' Ansell <mithro@mithis.com>
    - HDMI2USB Project - https://hdmi2usb.tv <hdmi2usb@googlegroups.com>
